name: Build

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Do the build
        run: echo "A build step" >> README.md

      - name: Upload the build
        uses: actions/upload-artifact@v4
        with:
          name: build_artifact
          path: README.md

  not_production:
    uses: ./.github/workflows/release.yml
    needs: build
    with:
      environment: not-production
