name: Manual Release

on:
  workflow_dispatch:
    inputs:
      build:
        description: "Build to release"
        required: true

      environment:
        description: "Environment to release to"
        required: true
        default: "uat"
        type: choice
        options:
          - uat
          - production

jobs:
  trigger:
    uses: ./.github/workflows/release.yml
    with:
      environment: ${{ inputs.environment }}
      build: ${{ inputs.build }}
