name: Manual Release

on:
  workflow_dispatch:
    inputs:
      build:
        description: "Build to release"
        default: "1.0.0"

      environment:
        description: "Environment to release to"
        required: true
        default: "uat"
        type: choice
        options:
          - uat
          - production

jobs:
  trigger_release:
    runs-on: ubuntu-latest

    steps:
      - name: Release
        uses: ./.github/workflows/release.yml
        with:
          environment: ${{ inputs.environment }}
          build: ${{ inputs.build }}
