name: Release

on:
  workflow_call:
    inputs:
      build:
        description: "Build to release"
        required: true
        type: string

      environment:
        description: "Environment to release to"
        default: "uat"
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Download the build
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.inputs.build }}

      - name: Would deploy
        run: |
          echo "Would deploy to $ENVIRONMENT"
          echo "Using build $BUILD"
          ls -l
          cat README.md
        env:
          BUILD: ${{ github.event.inputs.build }}
          ENVIRONMENT: ${{ github.event.inputs.environment }}
