name: Release
run-name: Release to ${{ inputs.environment }}

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to release to"
        type: string
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Download the build
        uses: actions/download-artifact@v4
        with:
          path: target

      - name: Got secrets?
        run: |
          echo "The secret is ${#THE_SECRET}"
          echo "The secret is ${{ secrets.SECRET_KEY }}"
        env:
          THE_SECRET: ${{ secrets.SECRET_KEY }}

      - name: Got variables?
        run: |
          echo "The variaable is $THE_VARIABLE"
        env:
          THE_VARIABLE: ${{ vars.NOT_SECRET_KEY }}

      - name: Would deploy
        run: |
          echo "Would deploy to $ENVIRONMENT"
          ls -lR
          cat target/build_artifact/README.md
        env:
          ENVIRONMENT: ${{ inputs.environment }}
