name: Release
run-name: Release to ${{ inputs.environment }}

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to release to"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      actions: read

    steps:
      - name: Download the build
        uses: actions/download-artifact@v4
        with:
          path: target

      - name: Would deploy
        run: |
          echo "Would deploy to $ENVIRONMENT"
          ls -lR
          cat target/build_artifact/README.md
        env:
          ENVIRONMENT: ${{ inputs.environment }}
